language: ruby
rvm:
- 2.0.0
- 2.1.4
before_script:
  - psql -c 'create database unique_attributes_test;' -U postgres
script: bundle exec rspec
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 77d19511a3073b3dcadd6b4abbc87e5dd46c3db1ba6815a32545e91d9996d820
notifications:
  email: false
  hipchat:
    rooms:
      secure: Q3zxZGqtrcbhw3S038A1LSmWks5uEKxKUjGee5q30PWCkoNEg9VxgbcMH2ZzMA10BCvHcKMI4yUk7yy/WyO8UKYprFA8707M7FjBmxfY62GK9K58sPBDUrnpCAfxGqyZZ1oXofSJamNPHh3G8U18yZhWt4j/5XHrwzBo8+p/0bI=
